return {
    boundfield = require"resty.mvc.boundfield",
    datetime = require"resty.mvc.datetime",
    form = require"resty.mvc.form",
    formfield = require"resty.mvc.formfield",
    init = require"resty.mvc.init",
    manager = require"resty.mvc.manager",
    migrate = require"resty.mvc.migrate",
    model = require"resty.mvc.model",
    modelfield = require"resty.mvc.modelfield",
    q = require"resty.mvc.q",
    query = require"resty.mvc.query",
    request = require"resty.mvc.request",
    response = require"resty.mvc.response",
    row = require"resty.mvc.row",
    template = require"resty.mvc.template",
    utils = require"resty.mvc.utils",
    validator = require"resty.mvc.validator",
    view = require"resty.mvc.view",
    widget = require"resty.mvc.widget",
    apps = require"resty.mvc.apps",
    admin = require"resty.mvc.admin",
    router = require"resty.mvc.router",
}